spring:
  application:
    name: 'lalingua'
  datasource:
    #    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    url: jdbc:mysql://127.0.0.1:3306/auth?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
jwt:
  access:
    issuer: ME
    key: MY_SECRET_KEY!
    expiration: 30000
  refresh:
    expiration: 30000
    length: 24
server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: test
    key-store-type: PKCS12
    key-alias: myalias
logging:
  level:
    org.springframework.web: "debug"
    org.springframework.security: "debug"
    org.hibernate: "trace"